### PR TITLE
made js folder and main.js file

### PR DESCRIPTION
**Pull request by ghost**
js folder & file

### CODE REVIEW

**Comment by ghost** [comment]
actually filename is: products.js

**Comment by ghost** [comment]
moved products.js into js folder

**Comment by wocaldwell** [comment]
There is an extra products.js on the root. Remove that and we will be good!

**Comment by ghost** [comment]
at this point we should have different pictures on index.html, products.html, and employees.html

**Comment by caseydailey** [comment]
👍

**Comment by wocaldwell** [comment]
A-okay!! 👍

**Pull request merged**
