### PR TITLE
plugged in the js. and updated descriptions and prices

### PR DESCRIPTION
**Pull request by caseydailey**

### CODE REVIEW

**Comment by ghost** [comment]
it's working! now we're just tweaking the overflow & padding in the articles

**Comment by wocaldwell** [comment]
Change line 29 on products.ccs to padding-top: 1%;. And change line 34 to overflow: scroll;.

**Comment by ghost** [comment]
👍

**Comment by wocaldwell** [comment]
:

**Comment by wocaldwell** [comment]
👍

**Pull request merged**
