### PR TITLE
Woc history

### PR DESCRIPTION
**Pull request by wocaldwell**
Finished history page. Also updated slogan on other pages. added the selected class and on hover color for page links.

### CODE REVIEW

**Comment by ghost** [comment]
looks great, love the house!

**Comment by caseydailey** [comment]
👍

**Comment by ghost** [comment]
now we just need to add a field/windmill background image to this page with this code:

#main-head {
  background-image: url("../images/fieldwindmill-copy.jpg");
  backgrounds-blend-mode: screen;
  background-repeat: no-repeat;
}

**Comment by wocaldwell** [comment]
added image to background. changed slogan on product page.

**Comment by caseydailey** [comment]
👍

**Pull request merged**
